### ISSUE TITLE
After leaving search prompt, chatGPT changes the folder 

### ISSUE THREAD

**Issue by abneb** [Axlfc/UE5-python#2]
Hey Axlfc, 
Find another behavior to fix I guess. 
I follow the Content instalation. So when I call chatGPT from terminal everything goes fine. But when I'm exit with <C-c> it changes my terminal prompt from the folder I'm in to chatGPT/Content/Python/chatGPT.

![chatGPT_error](https://user-images.githubusercontent.com/69637662/208747338-64a19284-53b6-4f7b-b539-75258c4b5111.png)

**Comment by Axlfc** [comment]
This happenned because the bash function in customizer didn't run inside a subshell. Now this problem is solved. The solution was to run the cd inside () to avoid changing path when interrupted execution.

![imagen](https://user-images.githubusercontent.com/14998495/208769536-4d7b36a2-85cf-4494-9432-f25a3bfa672a.png)

Adding the parenthesis in [this code](https://github.com/AleixMT/Linux-Auto-Customizer/blob/chatGPT_feature/data/features/chatGPT/chatGPT.sh) protecting the cd fixed this issue.

Make sure to update Linux-Auto-Customizer repository folder **in chatGPT_feature branch**:
<code>git pull</code>
To refresh the changes.

Save your .env file with the API key in a safe place before re-install so you don't lose it, and paste it back after the installation.
With a copy of .env file in safe place, now you can try to reinstall the feature, to do so re-run the install.sh script as you did the first time after pulling the last changes from the repository.

After the `git pull` command, run again:
<code>bash src/core/install.sh -v -o -f chatGPT</code>

Paste back the .env file in ~/.customizer/bin/chatGPT/Content/Python/chatBot directory and everything should work fine now.

Thanks a lot for letting me know and for the help in test!!

**Comment by abneb** [comment]
Great Axlfc!
I tested and it was fixed. 
Keep going use it.
