### ISSUE TITLE
First two characters missing

### ISSUE THREAD

**Issue by Celtic-Knot** [Axlfc/UE5-python#7]
I have installed this in Termux, all working except that the first two characters of any reply (using chatgpt) are missing. Third character onwards all fine so just a niggle as I can normally work it out. Any idea what code needs changing? Thank you.

![ksnip_20230430-192945](https://user-images.githubusercontent.com/52403502/235370278-c4a6e834-fc1f-4e09-b998-9ddff6d8176a.png)

**Comment by Axlfc** [comment]
It's probably something with line 85 from [bot.py](https://github.com/Axlfc/UE5-python/blob/master/Content/Python/chatBot/bot.py).

<code>return str(completion.choices[0]).split("content")[1][6:].split("role")[0][:-1].replace('\\n', '\n')[:-7].encode('utf-8').decode('unicode_escape')</code>

You can try changing it to:

<code>return str(completion.choices[0]).split("content")[1][6:].split("role")[0][:-1].replace('\\n', '\n')[:-5].encode('utf-8').decode('unicode_escape')</code>
                   

I'm unavailable to make any tests due to I have no valid openai API key.

**Comment by Celtic-Knot** [comment]
Thank you! It was that line in that file, though the code that corrected it was as follows:

`return str(completion.choices[0]).split("content")[1][4:].split("role")[0][:-1].replace('\n', '\n')[:-7].encode('utf-8').decode('unicode_escape')`

I am sorry I am not a coder; I have corrected my own code, but not sure of proper way to make the above amendment as a suggestion to your code here on github. Thanks again for showing where to look.
